- name: Install base packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - curl
    - git
    - wget
    - vim
    - htop
    - iptables-persistent
    - net-tools
    - lsof
    - tcpdump
    - python3-pip
    - python3-setuptools

- name: Update the system
  apt:
    upgrade: dist
    update_cache: yes

- name: Add Debian Backports repository
  apt_repository:
    repo: 'deb http://deb.debian.org/debian buster-backports main'
    state: present

- name: Install latest docker-ce from backports
  apt:
    name: docker-ce
    state: present
    update_cache: yes

- name: Install docker-compose plugin
  pip:
    name: docker-compose
    executable: pip3

- name: Create required directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - /etc/prometheus
    - /var/lib/grafana
    - /usr/local/bin