---
- name: Deploy Prometheus Node Exporter, MariaDB, MySQL Exporter and configure NFTABLES on Debian 12
  hosts: all
  become: yes
  gather_facts: true

  tasks:
    - name: Install required packages for Prometheus Node Exporter
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - unzip
        - wget

    - name: Download Prometheus Node Exporter binary
      get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v1.4.0/node_exporter-1.4.0.linux-amd64.tar.gz
        dest: /tmp/node_exporter.tar.gz
        mode: 0644

    - name: Extract Prometheus Node Exporter archive
      unarchive:
        src: /tmp/node_exporter.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Copy Prometheus Node Exporter binary to bin folder
      copy:
        src: /opt/node_exporter-1.4.0.linux-amd64/node_exporter
        dest: /usr/local/bin/node_exporter
        mode: 0755

    - name: Create SystemD service file for Prometheus Node Exporter
      template:
        src: templates/node_exporter.service.j2
        dest: /etc/systemd/system/node_exporter.service
        owner: root
        group: root
        mode: 0644

    - name: Start and enable Prometheus Node Exporter service
      systemd:
        name: node_exporter
        enabled: yes
        state: started
        daemon_reload: yes

    - name: Install MariaDB Server
      apt:
        name: mariadb-server
        state: present
        update_cache: yes

    - name: Install NFTABLES package
      apt:
        name: nftables
        state: present
        update_cache: yes

    - name: Enable and start NFTABLES service
      systemd:
        name: nftables
        enabled: yes
        state: started

    - name: Configure basic NFTABLES firewall rules
      blockinfile:
        path: /etc/nftables.conf
        content: |
          flush ruleset

          table inet filter {
              chain input {
                  type filter hook input priority 0;

                  ct state established,related accept
                  iif lo accept
                  ip saddr {{ trusted_network }} accept
                  tcp dport ssh accept

                  reject with icmp type port-unreachable
              }
          }
